### ISSUE TITLE
Network status says "unknown" even when connected

### ISSUE THREAD

**Issue by FROGbots-4634** [ftctechnh/ftc_app#560]
It appears that there is a bug in SDK v4.0 which causes the network status to be listed as "unknown" even when it is connected. Have a look at the network status TextView on the RC:

![img_5629 - copy](https://user-images.githubusercontent.com/26417650/45561801-9ac20d00-b816-11e8-8050-f742bea23cc2.JPG)

Steps to reproduce:

1) Open RC app
2) Open DS app
3) Wait for the DS to connect to the RC

Reproduced on the following devices and OS versions: Nexus 5, Nexus 7 2013, 6.0.1, 7.1.2

**Comment by SpyGuyIan** [comment]
We were having a similar issue. The phones were connected through WiFi-Direct in settings and through the "Pair Robot Controller" on the DS, but there was no ping (it was blank) and we also got "Network: unknown, connected". All would be fine if we could still run opmodes but the menus are all blank.

We are running on two Moto G5 devices

**Comment by cmacfarl** [comment]
The lack of ping on @SpyGuyIan's phones is not necessarily related to the network status reported here.  The network status indication will be fixed in the next point release.  

@SpyGuyIan, can you please swipe close, or force stop, both the DS and RC, start the RC, and then start the DS?  If they do not pair and you do not get pings please open a new issue and attach both the DS and RC log.

**Comment by FROGbots-4634** [comment]
Fixed a long time ago, in SDK v5.1 I believe
