### ISSUE TITLE
Method getInstance() not found in ClassFactory

### ISSUE THREAD

**Issue by cwongmath** [ftctechnh/ftc_app#609]
The method getInstance() isn't found in the class ClassFactory. It always returns a build error: 
![image](https://user-images.githubusercontent.com/32407067/47320284-9c9d9e00-d616-11e8-9314-7c1f39ad1d45.png)
The error happens in any Vuforia sample files.

**Comment by JBYoshi** [comment]
Try refreshing your Gradle project.

**Comment by dmssargent** [comment]
@JBYoshi Refreshing the Gradle project is rather useless as OnBotJava doesn't interact with Gradle in this context.

**Comment by gearsincorg** [comment]
This error is caused because an older OnBotJava library is hanging around on your RC phone.

One effective way to correct this problem is to let the new App completely reset the OnBotJava subsystem on the phone. There is an "Advanced" setting to permit this on the OnBotJava web interface.

Before making any changes though, I'd download any OnBotJava Opmodes you have on your RC to your computer as a backup. Simply right click on them (in the tree) and select download...

To reset the OBJ system, follow these directions:

!!!!! MAKE sure you have downloaded any OpModes you want to keep, BEFORE doing this...!!!!!

1. Start up the RC app and use your browser to connect to your phone just like you would if you were doing OnBotJava programming.
2. Select OnBotJava, and click on the Settings (GEAR) icon.
3. Scroll down to, and expand the "Advanced Settings" option
4. Click on the RED "RESET" button.
5. You will be prompted if you really want to do this: Click OK 
   And you will be prompted AGAIN... and actually have to type "Yes I want to". Do it!

Now, if you return to the OnBotJava page, all the opmodes will be gone and you should be able to either re-create them, or restore your saved opmodes by using the Upload Files icon.

**Comment by cwongmath** [comment]
The latest comment worked. Thanks so much!
