### ISSUE TITLE
Vuforia isn't updated for Rover Ruckus

### ISSUE THREAD

**Issue by cwongmath** [ftctechnh/ftc_app#611]
The sample Vuforia files aren't updated for Rover Ruckus as RelicRecoveryVuMark is located in the files, and the phone only recognizes last year's VuMarks.

**Comment by cmacfarl** [comment]
Do you not see ConceptVuforiaNavRoverRuckus in FtcRobotController/external.samples?

**Comment by cwongmath** [comment]
Heh. Whoops.

**Comment by rickliner** [comment]
The training documentation on the FIRST Web Site for using Vuforia has not
been updated since the 2017 season and only refers to the prior game.
https://www.firstinspires.org/resource-library/ftc/game-and-season-info
https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/using-vumarks.pdf
